[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=604800"
  for = "*.mjs"
  [headers.values]
    Cache-Control = "public, max-age=604800"    
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"    